name: MiPrimerWorkflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        MI_VARIABLE: "¡Hola desde GitHub Actions!"

    steps:
        - name: Mostrar Variable
          run: echo "El valor de la variable es $MI_VARIABLE"
  